### PR TITLE
Mvp fixes

### PR DESCRIPTION
**Pull request by Hazmid**
- Used Embed page design for Home and ward page
- Hide ward office and muni office pin
- Hide blank email fields
- Used placeholder image for ward councillor image
- clean up

### CODE REVIEW

**Review by cyber237 — COMMENTED** [review]
@Hazmid a test is failing because the template here_for_change/municipalities/templates/municipalities/home.html starts with a section tag and not Doctype

**Comment by Hazmid** [comment]
> 

@cyber237 Okay, thanks. I will fix that.

**Review by cyber237 — COMMENTED** [review]
@Hazmid find ward councillor page is included in home page but has doctype,html,head and body tags. This causes IndexTestCase to fail when asserting if the home page html content is valid.

Proposed solution:
- Find a way to seperate 'find ward councillor tool' from 'find ward councillor page'.
- The seperated 'find ward councillor tool ' could then be embedded in 'find ward councillor page' and 'home page'.

If you need clarification, please don't hesitate to ask.

**Comment by Hazmid** [comment]
@cyber237  The 'find ward councillor tool' has been separated from 'find ward councillor page'. The tests should pass now.

**Pull request merged**
