### PR TITLE
Initialize tailwind

### PR DESCRIPTION
**Pull request by Hazmid**
### Tailwind setup:

Navigate to **here_for_change > jstoolchain** 
run `npm install`

## for development

In your jstoolchains folder, keep running `npm run tailwind-watch` while you're coding. 
This will ensure that your output.css file is regenerated as soon as you add a new tailwind class to your code. 

##for production

Run `npm run tailwind-build`
This will build the output and remove unused classes to ensure a lower file size.

### CODE REVIEW

**Comment by paulmwatson** [comment]
What is the reason for removing `/package.json` and creating `/here_for_change/jstoolchain/package.json`?

**Comment by Hazmid** [comment]
The `Jstoolchain > package.json` is for managing tailwind in a django project. I did not realize the `package.json` in root got deleted, What was the use of the `package.json` in the root of this Django project?

**Comment by paulmwatson** [comment]
It is used for parcel and serving.

**Comment by Hazmid** [comment]
okay, That's fine.

**Pull request merged**
